services:
  - type: web
    name: qr-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python qr_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    plan: free
